### ISSUE TITLE
Unexpected output!?

### ISSUE THREAD

**Issue by foobargeez** [ap/titlecase#4]
Hello,

```
use Lingua::EN::Titlecase::Simple 'titlecase';
print titlecase("100's"), "\n";
```

I am expecting the output would be `100's` and not `100'S`.  I verified this with http://titlecase.com/ and it is returning `100's`.  Wanted to report to see if this can be fixed (assuming you agree this is an issue).

Thanks in advance!

**Comment by ap** [comment]
Thanks for the report.

It will take me a couple days to get this to the CPAN since I’ve been retooling the distro and haven’t finished. (Your timing is lucky in that I just cut my first release of a retooling job in another distro, so I now have a template to work off of for this one, and thus I can expect it to have it done within days rather than at some indefinite point.)

**Comment by ap** [comment]
It’s now on its way to the CPAN. Share and enjoy. 😊

**Comment by foobargeez** [comment]
Thanks, appreciate your quick turnaround.
